import type { BookingSlot, GalleryItem, Review, ServiceItem } from './types.js';

/**
 * Cjenik salona DEEP BLUE (usklađen s grafičkim cjenikom salona).
 * Depilacija: `priceEur` = žene (Ž), `priceEurMen` = muškarci (M).
 */
export const mockServices: ServiceItem[] = [
  // —— Uklanjanje dlačica / Waxing ——
  {
    id: 'wax-face',
    name: 'Depilacija lica / Waxing face',
    category: 'waxing',
    durationMin: 0,
    priceEur: 10,
    description: '',
  },
  {
    id: 'wax-upper-lip',
    name: 'Depilacija nadusnice / Waxing upper lip',
    category: 'waxing',
    durationMin: 0,
    priceEur: 5,
    description: '',
  },
  {
    id: 'wax-armpits',
    name: 'Depilacija pazuha / Waxing armpits',
    category: 'waxing',
    durationMin: 0,
    priceEur: 10,
    priceEurMen: 15,
    description: '',
  },
  {
    id: 'wax-arms',
    name: 'Depilacija ruku / Waxing arms',
    category: 'waxing',
    durationMin: 0,
    priceEur: 15,
    priceEurMen: 20,
    description: '',
  },
  {
    id: 'wax-bikini',
    name: 'Depilacija bikini zone / Waxing bikini zone',
    category: 'waxing',
    durationMin: 0,
    priceEur: 15,
    description: '',
  },
  {
    id: 'wax-brazilian',
    name: 'Brazilska depilacija / Brazilian wax',
    category: 'waxing',
    durationMin: 0,
    priceEur: 25,
    description: '',
  },
  {
    id: 'wax-back',
    name: 'Depilacija leđa / Waxing back',
    category: 'waxing',
    durationMin: 0,
    priceEur: 10,
    priceEurMen: 20,
    description: '',
  },
  {
    id: 'wax-belly',
    name: 'Depilacija trbuha / Waxing belly',
    category: 'waxing',
    durationMin: 0,
    priceEur: 10,
    priceEurMen: 20,
    description: '',
  },
  {
    id: 'wax-lower-legs',
    name: 'Depilacija potkoljenice / Waxing lower legs',
    category: 'waxing',
    durationMin: 0,
    priceEur: 15,
    priceEurMen: 20,
    description: '',
  },
  {
    id: 'wax-upper-legs',
    name: 'Depilacija nadkoljenice / Waxing upper legs',
    category: 'waxing',
    durationMin: 0,
    priceEur: 15,
    priceEurMen: 20,
    description: '',
  },
  {
    id: 'wax-full-legs',
    name: 'Depilacija cijelih nogu / Waxing whole legs',
    category: 'waxing',
    durationMin: 0,
    priceEur: 30,
    priceEurMen: 35,
    description: '',
  },
  {
    id: 'wax-legs-bikini',
    name: 'Depilacija cijelih nogu i bikini zone / Waxing whole legs with bikini zone',
    category: 'waxing',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'wax-legs-deep-bikini',
    name: 'Depilacija cijelih nogu i duboki bikini / Waxing whole legs with deep bikini',
    category: 'waxing',
    durationMin: 0,
    priceEur: 40,
    description: '',
  },
  {
    id: 'wax-legs-brazilian',
    name: 'Depilacija cijelih nogu i brazilska / Waxing whole legs with Brazilian',
    category: 'waxing',
    durationMin: 0,
    priceEur: 45,
    description: '',
  },
  {
    id: 'wax-brows-shape',
    name: 'Oblikovanje obrva / Eyebrow shaping',
    category: 'waxing',
    durationMin: 0,
    priceEur: 10,
    description: '',
  },
  {
    id: 'wax-brows-color',
    name: 'Bojanje obrva / Eyebrows coloring',
    category: 'waxing',
    durationMin: 0,
    priceEur: 10,
    description: '',
  },
  {
    id: 'wax-brows-both',
    name: 'Oblikovanje i bojanje obrva / Eyebrow shaping and coloring',
    category: 'waxing',
    durationMin: 0,
    priceEur: 15,
    description: '',
  },

  // —— Tretmani lica / Facials ——
  {
    id: 'face-massage',
    name: 'Masaža lica / Facial massage',
    category: 'face',
    durationMin: 0,
    priceEur: 20,
    description: '',
  },
  {
    id: 'face-by-type',
    name: 'Njega lica po tipu kože / Facial care according to skin type',
    category: 'face',
    durationMin: 0,
    priceEur: 25,
    description: '',
  },
  {
    id: 'face-with-massage',
    name: 'Njega lica s masažom / Facial care with massage',
    category: 'face',
    durationMin: 0,
    priceEur: 40,
    description: '',
  },
  {
    id: 'face-oxy',
    name: 'Njega lica + OXY / Facial care + OXY',
    category: 'face',
    durationMin: 0,
    priceEur: 45,
    description: '',
  },
  {
    id: 'face-rf',
    name: 'Njega lica + radiofrekvencija / Facial care + radiofrequency',
    category: 'face',
    durationMin: 0,
    priceEur: 60,
    description: '',
  },
  {
    id: 'face-ultrasound-cleanse',
    name: 'Ultrazvučno čišćenje lica / Ultrasound facial cleansing',
    category: 'face',
    durationMin: 0,
    priceEur: 45,
    description: '',
  },
  {
    id: 'face-mechanical-cleanse',
    name: 'Mehaničko čišćenje lica / Mechanical facial cleansing',
    category: 'face',
    durationMin: 0,
    priceEur: 50,
    description: '',
  },
  {
    id: 'face-neck-decollete',
    name: 'Tretman lica, vrata i dekoltea / Face, neck and décolletage treatment',
    category: 'face',
    durationMin: 0,
    priceEur: 60,
    description: '',
  },

  // —— Dermaroller ——
  {
    id: 'derma-roller-1',
    name: 'Dermaroller 1 tretman / Dermaroller 1 treatment',
    category: 'derma',
    durationMin: 0,
    priceEur: 55,
    description: '',
  },
  {
    id: 'derma-pen-1',
    name: 'Dermapen 1 tretman / Dermapen 1 treatment',
    category: 'derma',
    durationMin: 0,
    priceEur: 65,
    description: '',
  },
  {
    id: 'derma-roller-5',
    name: 'Dermaroller 5 tretmana / Dermaroller 5 treatments',
    category: 'derma',
    durationMin: 0,
    priceEur: 115,
    description: '',
  },
  {
    id: 'derma-combo',
    name: 'Dermaroller 5 tretmana + Dermapen 1 tretman / Dermaroller 5 treatments + Dermapen 1 treatment',
    category: 'derma',
    durationMin: 0,
    priceEur: 150,
    description:
      'Uz jedan od odabranih tretmana dobivate Dermaroller. / With one of the selected treatments you will get a Dermaroller.',
  },

  // —— Madero ——
  {
    id: 'madero-ac-30',
    name: 'Anti-celulitna 30 min / Anti-cellulite 30 min',
    category: 'madero',
    durationMin: 30,
    priceEur: 30,
    description: '',
  },
  {
    id: 'madero-ac-45',
    name: 'Anti-celulitna 45 min / Anti-cellulite 45 min',
    category: 'madero',
    durationMin: 45,
    priceEur: 35,
    description: '',
  },
  {
    id: 'madero-face-30',
    name: 'Lice 30 min / Face 30 min',
    category: 'madero',
    durationMin: 30,
    priceEur: 25,
    description: '',
  },
  {
    id: 'madero-back-30',
    name: 'Leđa 30 min / Back 30 min',
    category: 'madero',
    durationMin: 30,
    priceEur: 25,
    description: '',
  },

  // —— Masaže ——
  {
    id: 'mass-feet-30',
    name: 'Masaža stopala 30 min / Foot massage 30 min',
    category: 'massage',
    durationMin: 30,
    priceEur: 25,
    description: '',
  },
  {
    id: 'mass-classic-30',
    name: 'Klasična masaža 30 min / Classical massage 30 min',
    category: 'massage',
    durationMin: 30,
    priceEur: 30,
    description: '',
  },
  {
    id: 'mass-sport-30',
    name: 'Sportska masaža 30 min / Sports massage 30 min',
    category: 'massage',
    durationMin: 30,
    priceEur: 35,
    description: '',
  },
  {
    id: 'mass-classic-50',
    name: 'Klasična masaža 50 min / Classical massage 50 min',
    category: 'massage',
    durationMin: 50,
    priceEur: 40,
    description: '',
  },
  {
    id: 'mass-sport-50',
    name: 'Sportska masaža 50 min / Sports massage 50 min',
    category: 'massage',
    durationMin: 50,
    priceEur: 45,
    description: '',
  },
  {
    id: 'mass-aroma-candle-50',
    name: 'Aroma masaža sa svijećom 50 min / Aroma massage with candle 50 min',
    category: 'massage',
    durationMin: 50,
    priceEur: 45,
    description: '',
  },

  // —— Tretmani za tijelo ——
  {
    id: 'body-thermal-blanket',
    name: 'Termo deka 45 min / Thermal blanket 45 min',
    category: 'body',
    durationMin: 45,
    priceEur: 25,
    description: '',
  },
  {
    id: 'body-wrap',
    name: 'Body wrapping 45 min / Body wrapping treatment 45 min',
    category: 'body',
    durationMin: 45,
    priceEur: 25,
    description: '',
  },
  {
    id: 'body-ac-massage-30',
    name: 'Anti-celulitna masaža 30 min / Anti-cellulite massage 30 min',
    category: 'body',
    durationMin: 30,
    priceEur: 30,
    description: '',
  },
  {
    id: 'body-vacuslim',
    name: 'VACUSLIM 48 Anti-celulitni tretman / VACUSLIM 48 Anti-cellulite treatment',
    category: 'body',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'body-uzv-15',
    name: 'UZV 15 min',
    category: 'body',
    durationMin: 15,
    priceEur: 15,
    description: '',
  },
  {
    id: 'body-lymph-20',
    name: 'Limfna drenaža 20 min / Lymphatic drainage 20 min',
    category: 'body',
    durationMin: 20,
    priceEur: 20,
    description: '',
  },
  {
    id: 'body-lymph-40',
    name: 'Limfna drenaža 40 min / Lymphatic drainage 40 min',
    category: 'body',
    durationMin: 40,
    priceEur: 25,
    description: '',
  },

  // —— Nokti ——
  {
    id: 'nails-hand-care',
    name: 'Njega ruku / Hand care – manicure',
    category: 'nails',
    durationMin: 0,
    priceEur: 20,
    description: '',
  },
  {
    id: 'nails-hand-regular',
    name: 'Njega ruku s običnim lakom / Hand care – manicure with ordinary nail polish',
    category: 'nails',
    durationMin: 0,
    priceEur: 25,
    description: '',
  },
  {
    id: 'nails-hand-long',
    name: 'Njega ruku s trajnim lakom / Hand care – manicure with long-lasting nail polish',
    category: 'nails',
    durationMin: 0,
    priceEur: 30,
    description: '',
  },
  {
    id: 'nails-gel-natural',
    name: 'Gel nokti prirodna dužina / Gel nails natural length',
    category: 'nails',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'nails-gel-ext-s',
    name: 'Gel nokti nadogradnja S / Gel nails extension S',
    category: 'nails',
    durationMin: 0,
    priceEur: 40,
    description: '',
  },
  {
    id: 'nails-gel-ext-m',
    name: 'Gel nokti nadogradnja M / Gel nails extension M',
    category: 'nails',
    durationMin: 0,
    priceEur: 45,
    description: '',
  },
  {
    id: 'nails-gel-ext-l',
    name: 'Gel nokti nadogradnja L / Gel nails extension L',
    category: 'nails',
    durationMin: 0,
    priceEur: 50,
    description: '',
  },
  {
    id: 'nails-gel-refill-s',
    name: 'Gel nokti nadopuna S / Gel nails refills S',
    category: 'nails',
    durationMin: 0,
    priceEur: 30,
    description: '',
  },
  {
    id: 'nails-gel-refill-m',
    name: 'Gel nokti nadopuna M / Gel nails refills M',
    category: 'nails',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'nails-gel-refill-l',
    name: 'Gel nokti nadopuna L / Gel nails refills L',
    category: 'nails',
    durationMin: 0,
    priceEur: 40,
    description: '',
  },
  {
    id: 'nails-repair',
    name: 'Popravak nokta Evo2 ili gel / Nail repair Evo2 or gel',
    category: 'nails',
    durationMin: 0,
    priceEur: 5,
    description: '',
  },
  {
    id: 'nails-french',
    name: 'French / French',
    category: 'nails',
    durationMin: 0,
    priceEur: 5,
    description: '',
  },
  {
    id: 'nails-art',
    name: 'Crtanje / Nail art',
    category: 'nails',
    durationMin: 0,
    priceEur: 10,
    description: '',
  },
  {
    id: 'nails-remove',
    name: 'Uklanjanje trajnog laka ili gela / Removing long-lasting nail polish or gel',
    category: 'nails',
    durationMin: 0,
    priceEur: 20,
    description: '',
  },
  {
    id: 'nails-foot-regular',
    name: 'Obični lak noge / Ordinary nail polish on feet',
    category: 'nails',
    durationMin: 0,
    priceEur: 25,
    description: '',
  },
  {
    id: 'nails-foot-long',
    name: 'Trajni lak noge / Long-lasting nail polish on feet',
    category: 'nails',
    durationMin: 0,
    priceEur: 30,
    description: '',
  },
  {
    id: 'nails-pedicure',
    name: 'Njega stopala / Foot care – pedicure',
    category: 'nails',
    durationMin: 0,
    priceEur: 30,
    description: '',
  },
  {
    id: 'nails-med-pedicure',
    name: 'Medicinska pedikura / Medical pedicure',
    category: 'nails',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'nails-collagen-bath',
    name: 'Collagen kupka za stopala s masažom stopala / Collagen foot bath with foot massage',
    category: 'nails',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'nails-pedicure-regular',
    name: 'Njega stopala s običnim lakom / Foot care – pedicure with ordinary nail polish',
    category: 'nails',
    durationMin: 0,
    priceEur: 35,
    description: '',
  },
  {
    id: 'nails-pedicure-long',
    name: 'Njega stopala s trajnim lakom / Foot care – pedicure with long-lasting nail polish',
    category: 'nails',
    durationMin: 0,
    priceEur: 40,
    description: '',
  },
  {
    id: 'nails-collagen-spa',
    name: 'Collagen SPA pedikura / Collagen SPA pedicure',
    category: 'nails',
    durationMin: 0,
    priceEur: 45,
    description: '',
  },
  {
    id: 'nails-collagen-spa-long',
    name: 'Collagen SPA pedikura s trajnim lakom / Collagen SPA pedicure with long-lasting nail polish',
    category: 'nails',
    durationMin: 0,
    priceEur: 55,
    description: '',
  },

  // —— Poklon bonovi ——
  {
    id: 'gift-voucher',
    name: 'Poklon bonovi / Gift cards',
    category: 'gift',
    durationMin: 0,
    priceEur: 0,
    description: 'Cijena prema odabranom tretmanu / Price according to the chosen treatment.',
  },
];

export const mockGallery: GalleryItem[] = [
  {
    id: 'g-1',
    title: 'Tretmani lica',
    imageUrl: 'https://images.unsplash.com/photo-1616394584738-fc7e012d4364?w=800&q=80',
    caption: 'Njega kože lica — uz mogućnost dijagnostike (npr. Wood lampa) prema ponudi salona.',
  },
  {
    id: 'g-2',
    title: 'Topao ambijent salona',
    imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    caption: 'DEEP BLUE — Zadar, Bana Josipa Jelačića 10 D.',
  },
  {
    id: 'g-3',
    title: 'Manikura i pedikura',
    imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80',
    caption: 'Nega noktiju u sklopu kozmetičke ponude.',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r-1',
    author: 'Ana M.',
    rating: 5,
    text: 'Stručan i ljubazan tim, osjećaj kao u hotelu — preporuka za Zadar.',
    date: '2026-03-02',
  },
  {
    id: 'r-2',
    author: 'Petra K.',
    rating: 5,
    text: 'Tretman lica i depilacija bez žurbe, sve uredno objašnjeno.',
    date: '2026-02-18',
  },
  {
    id: 'r-3',
    author: 'Iva R.',
    rating: 5,
    text: 'Za akcije pratim njihovu Facebook stranicu — usklađeno s onim što salon i piše na deepblue.hr.',
    date: '2026-01-30',
  },
];

export const mockSlots: BookingSlot[] = [
  { id: 'b-1', date: '2026-04-15', time: '09:00', available: true },
  { id: 'b-2', date: '2026-04-15', time: '10:30', available: true },
  { id: 'b-3', date: '2026-04-15', time: '12:00', available: false },
  { id: 'b-4', date: '2026-04-16', time: '11:00', available: true },
  { id: 'b-5', date: '2026-04-16', time: '15:30', available: true },
];
